name: track_slider
description: track_slider is a powerful and customizable track slider built with love using Flutter and Dart. Whether you're developing for iOS, Android, web, or desktop, this package has got you covered, providing a seamless experience across all Flutter platforms.
version: 0.0.3
homepage: https://github.com/uroojk844/track_slider

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
